### ISSUE TITLE
Provision load balancer using the ingress controller

### ISSUE THREAD

**Issue by Ozark9** [rohitrahi/vs-code-repo#2]
Hello,

I'm trying to complete the workshop "Developing Cloud Native Applications on OCI" but I'm running into a problem at practice 2-9 step 19. While trying to provision the load balancer using the ingress controller by running the command ""kubectl create -f vision-stays-app-lb.yaml" no Public IP address is getting assigned. 

```
[opc@developerenvironment kubernetes]$ kubectl get ingress
NAME                   CLASS    HOSTS   ADDRESS   PORTS     AGE
vision-stays-app-ing   <none>   *                 80, 443   8m49s
```

Until now I have used two versions of the ingress-nginx-contoller-deployment (v0.44.0 and v1.3.0) but the issue still persists.

```
$ cat vision-stays-app-lb.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vision-stays-app-ing
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - secretName: tls-secret
  rules:
  - http:
      paths:
      - path: /vs-hotels-dm
        pathType: ImplementationSpecific
        backend:
          service:
            name: hotel-service-svc
            port:
              number: 8081
      - path: /vs-customers
        pathType: ImplementationSpecific
        backend:
          service:
            name: customer-service-svc
            port:
              number: 8081
      - path: /vs-bookings
        pathType: ImplementationSpecific
        backend:
          service:
            name: booking-service-svc
            port:
              number: 8081
```

Please let me know what I need to modify in order to complete the workshop. Thank you in advance!

**Comment by Ozark9** [comment]
The below code worked:

`$ cat vision-stays-app-lb.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vision-stays-app-ing
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - secretName: tls-secret
  rules:
  - http:
      paths:
      - path: /vs-hotels-dm
        pathType: Prefix
        backend:
          service:
            name: hotel-service-svc
            port:
              number: 8081
      - path: /vs-customers
        pathType: Prefix
        backend:
          service:
            name: customer-service-svc
            port:
              number: 8081
      - path: /vs-bookings
        pathType: Prefix
        backend:
          service:
            name: booking-service-svc
            port:
              number: 8081`

**Comment by wazzutgm** [comment]
@Ozark9 , were you able to successfully do the curl to "http://<IngressLBpublic-ip>/vs-hotels/api/hotels/1001" step? I am hit with a 404 error. 
P.S. I do note the the hotel service is named as vs-hotels-dm in the ingress file. even that doesn't seem to work.

**Comment by mahendra-mehra** [comment]
try to redeploy ingress after changing pathType: Prefix to pathType: Implementationspecific

**Comment by wazzutgm** [comment]
Final version that worked for curl (it was "nginx.ingress.kubernetes.io/rewrite-target: /" which was causing the issue):

latest version of ingress nginx installed using the below command.

`kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.3.0/deploy/static/provider/cloud/deploy.yaml`

final ingress definition(vision-stays-app-lb.yaml):
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vision-stays-app-ing
spec:
  ingressClassName: nginx
  tls:
  - secretName: tls-secret
  rules:
  - http:
      paths:
      - path: /vs-hotels
        pathType: ImplementationSpecific
        backend:
          service:
            name: hotel-service-svc
            port:
              number: 8081
      - path: /vs-customers
        pathType: ImplementationSpecific
        backend:
          service:
            name: customer-service-svc
            port:
              number: 8081
      - path: /vs-bookings
        pathType: ImplementationSpecific
        backend:
          service:
            name: booking-service-svc
            port:
              number: 8081
```
